# Generated by Django 4.1.1 on 2022-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название игрушки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('dicription', models.CharField(max_length=255, verbose_name='Описание')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
