# Generated by Django 4.1.1 on 2022-09-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда последний раз обновлялись пароли?'),
        ),
    ]
