# Generated by Django 4.1.1 on 2022-09-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_users_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_modified',
        ),
    ]
