# Generated by Django 4.1.1 on 2022-09-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_toy_delete_toys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'managed': False},
        ),
    ]
