# Generated by Django 4.1.1 on 2022-09-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_users_options_alter_toy_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
